name: Deployment

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Deploy 

    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p ${{ vars.SSH_PORT }} ${{ vars.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy via Rsync
        run: |
          echo "Deploying to server..."
          rsync -az -e "ssh -p ${{ vars.SSH_PORT }} -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=yes" \
            --exclude='.git' \
            --exclude='.env' \
            --exclude='storage/*' \
            --exclude='public/storage' \
            ./ \
            ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }}:${{ vars.SSH_DIR }}
          echo "Rsync done."